version: '3'

services:
  gympass-style-app-pg:
    image: postgres:15.2-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRESQL_DB=gympass
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ${HOME}/.postgres-docker:/var/lib/postgresql/data
